### ISSUE TITLE
BtnGroup + Btn with input-type and input-value not setting checked state on radios/checkboxes

### ISSUE THREAD

**Issue by swright987** [wxsms/uiv#126] opened 2017-12-05 18:33 UTC
### Version & browser
Package:
uiv@0.14.3

Browser: 
Chrome@62.0.3202.94

### Which component
Btn

### Steps to reproduce the problem
Isolated to the following simplified component.
```
<template>
  <btn-group>
    <btn input-type="radio" input-value="1" v-model="model">Radio 1</btn>
    <btn input-type="radio" input-value="2" v-model="model">Radio 2</btn>
    <btn input-type="radio" input-value="3" v-model="model">Radio 3</btn>
    <btn input-type="radio" input-value="4" v-model="model" disabled>Radio 4 (Disabled)</btn>
  </btn-group>
</template>
<script>
import { Btn, BtnGroup } from 'uiv';

export default {
  data() {
    return {
      model: '1',
    };
  },
  components: {
    BtnGroup,
    Btn,
  },
};
</script>
```

### Expected behavior
Expecting model to update based on button clicks. Just viewing state using the vue inspector plugin.

### Actual behavior
Checkboxes or Radios don't get `checked="checked"` set so the state doesn't update. Cursory look seems like the inputType.validator is getting an object not a string. Will update when I have some more time to investigate.

**Comment by swright987** [comment] 2017-12-05 21:16
Started a fresh Vue project with the component above and all works as it should. Looking like this is likely a conflict between some other module in our project... perhaps lodash. Looking into it now.

**Comment by wxsms** [comment] 2017-12-06 01:41
https://codepen.io/wxsm/pen/ooOaeb

I can make this work.

Is there any error msgs?

**Comment by swright987** [comment] 2017-12-06 01:44
Nope. No errors. Just no change in the model. I had to wrap up work on something else this afternoon but I'll see if I can figure it out in the morning.

**Comment by swright987** [comment] 2017-12-08 15:36
change event isn't firing on click. the `active` class updates so the button looks right but the state doesn't update because on change isn't firing... still looking into it.
```
          on: {
            change: function() {
              console.log('changing');
              "checkbox" === u.inputType ? h ? u.value.splice(u.value.indexOf(u.inputValue), 1) : u.value.push(u.inputValue) : c.input(u.inputValue)
            }
          }
```

**Comment by wxsms** [comment] 2017-12-09 06:30
You don't need a change event on `btn`, it was handled inside the component, just add watchers to the model if you want to detect change.

**Comment by swright987** [comment] 2017-12-09 07:49
Correct. That's the change event in the uiv Btn component... It never fires in my project. The click event fires on the button but the change event doesn't fire on the radio inputs. I'll take another look tomorrow afternoon.

**Comment by wxsms** [comment] 2017-12-09 08:04
OK... I see. Which bundler you're using? browserify / webpack 1 or 2 / other? I will see if I can reproduce this.

**Comment by swright987** [comment] 2017-12-09 08:05
Webpack3 I believe... I'll check

**Comment by swright987** [comment] 2017-12-09 08:06
Nope. Weback 2.6.1

**Comment by swright987** [comment] 2017-12-09 08:12
Ugh was looking at the wrong branch. Yes webpack@3.5.1 and Vue@2.5.2

**Comment by swright987** [comment] 2017-12-09 08:22
I set up a separate project using the same webpack setup and the buttons work as they're supposed to. I haven't been able to nail down the issue within our main project yet however.

**Comment by wxsms** [comment] 2017-12-11 04:49
Closing due to this might not be an issue of uiv (can not repro). I will see what I can do once you found the root cause, thanks.

**Closed by wxsms** 2017-12-11 04:49 UTC
Labels: pending

**Comment by deepHackMode** [comment] 2018-01-18 12:47
Same issue with me as well. model is not getting updated.

Any update?

**Comment by swright987** [comment] 2018-01-18 20:23
@deepHackMode I ended up adding a separate click handler to update the values and moving on for now. I'd already spent too much time on it and it seemed to be a conflict outside of uiv after trying to reproduce it in it's own scaled down project. It would be nice to fix if you do figure it out. Thanks!

**Comment by StephenPCG** [comment] 2018-01-29 07:29
This may be caused by conflict to jquery. The following example will reproduce the problem:

```html
<!DOCTYPE html>
<html lang="en">
  <head>
    <link rel="stylesheet" href="https://cdn.bootcss.com/bootstrap/3.3.7/css/bootstrap.min.css">
  </head>
  <body>
    <div id="hello-world-app">
        <btn-group>
          <btn input-type="checkbox" input-value="1" v-model="model">Checkbox 1</btn>
          <btn input-type="checkbox" input-value="2" v-model="model">Checkbox 2</btn>
          <btn input-type="checkbox" input-value="3" v-model="model">Checkbox 3</btn>
          <btn input-type="checkbox" input-value="4" v-model="model" disabled>Checkbox 4 (Disabled)</btn>
        </btn-group>
        <hr/>
        <alert>Selected: {{model}}</alert>
    </div>

    <script src="https://cdn.bootcss.com/jquery/2.2.0/jquery.min.js"></script>
    <script src="https://cdn.bootcss.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/vue/2.1.6/vue.min.js"></script>
    <script src="https://unpkg.com/uiv"></script>
    <script>
      new Vue({
        el: "#hello-world-app",
        data() {
          return {
            model: ['1']
          }
        }
      });
    </script>
  </body>
</html>
```

If I remove `jquery.min.js`, it works just fine (but `bootstrap.min.js` would complain with "Bootstrap's JavaScript requires jQuery").

I'm a freshman with frontend dev, I don't know how to solve the conflict. @wxsms Can you please kindly provide some suggestions?

**Comment by wxsms** [comment] 2018-01-29 08:19
@StephenPCG jQuery is not the reason. `bootstrap.min.js` is. this pen has jQuery installed, and works fine: https://codepen.io/wxsm/pen/ooOaeb

However, this lib is intent to replace `bootstrap.min.js`, which means you should not use them in the same time. so this should not be a problem.

**Comment by StephenPCG** [comment] 2018-01-29 08:23
@wxsms Thanks a lot! I didn't know that. Actually, it's really shame that I even don't know what `bootstrap.min.js` is for (when should I include it), I'm just copying code from AdminLTE, and it includes `bootstrap.min.js`.

**Comment by bendytree** [comment] 2018-03-21 20:21
Is there any way to make `uiv` play nicely with `bootstrap.min.js`?

We're using `uiv` because we have a large project on bs3 and want to start doing some things with vue. Removing `bootstrap.min.js` is not an option because other parts of the page are using bs outside of vue.

I've got to think this is a common use-case for `uiv` - otherwise people would just use `bootstrap-vue`, right?

**Comment by wxsms** [comment] 2018-03-22 03:26
@bendytree I dont think that this is 'common', but If you need this badly, pls open another issue for it, and PRs are always welcome.
